# Generated by Django 4.1.7 on 2023-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=1000, verbose_name='Год публикации')),
                ('title', models.TextField(max_length=1000, verbose_name='Название статьи')),
                ('authors', models.TextField(max_length=1000, verbose_name='Авторы')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка на публикацию')),
            ],
        ),
    ]
