# Generated by Django 4.1.7 on 2023-04-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_user_delete_articles_article_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
    ]
