# Generated by Django 4.1.7 on 2023-05-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_author_article_teacher_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.teacher'),
        ),
    ]
