# Generated by Django 4.1.7 on 2023-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
